### ISSUE TITLE
Schema of the datasets

### ISSUE THREAD

**Issue by boramalper** [greenelab/crossref#13]
Hello and thanks for the data, much appreciated!

I am currently trying to assign a unique author ID to each author of each paper (from arXiv) given the paper's DOI. The task is trivial given the dataset, but I am just not sure which one to download since I have no clue about what information each dataset contains.

I think it would be great if you can share the schema of the datasets presented. For instance if it's a JSON object per newline, it would be great to share the first line at least, or even better, document it properly.

Since I am trying to solve the specific problem I mentioned in the first paragraph, I would also appreciate if you can direct me to the right dataset (if exist), whilst working on this issue.

Much thanks again,
Bora

**Comment by dhimmel** [comment]
Hey @boramalper thanks for the question. 

> I think it would be great if you can share the schema of the datasets presented

It would be nice our README's showed the head of each table in [`data`](https://github.com/greenelab/crossref/tree/master/data). We're not very actively maintaining this repository right now (although pull requests are welcome).

As a short-term solution, here are the first 5 rows of the compressed tables in `data`:

```
>>> curl --silent --location https://github.com/greenelab/crossref/raw/master/data/doi-to-issn.tsv.xz \
  | xzcat \
  | head --lines=6 \
  | column -t -s $'\t'
doi           issn
10.1001/.387  0003-9926
10.1001/.389  0003-9926
10.1001/.391  0003-9926
10.1001/.399  0003-9926
10.1001/.404  0003-9926

>>> curl --silent --location https://github.com/greenelab/crossref/raw/master/data/doi.tsv.xz \
  | xzcat \
  | head --lines=6 \
  | column -t -s $'\t'
doi           type             issued
10.1001/.387  journal-article  2006-02-27
10.1001/.389  journal-article  2006-02-27
10.1001/.391  journal-article  2006-02-27
10.1001/.399  journal-article  2006-02-27
10.1001/.404  journal-article  2006-02-27
```

As for the format of `crossref-works.json.xz`, this is a [JSON Lines](http://jsonlines.org/) formatted-file created using `mongoexport`. Each line is a Crossref record, so the schema for that JSON is whatever we get from the [Crossref API](https://github.com/CrossRef/rest-api-doc).

> I am currently trying to assign a unique author ID to each author of each paper (from arXiv) given the paper's DOI. The task is trivial given the dataset, but I am just not sure which one to download since I have no clue about what information each dataset contains.

Author disambiguation is very hard. If I understand your task, you are possibly looking for the ORCID of each author. I believe only a small percentage of authors have ORCID values set in Crossref. Most authors are just text names. I think this metadata has been improving, so you'd likely want to a recent Crossref dump.

Maybe it makes sense to prototype whether the method will work by just downloading the Crossref metadata for published-arxiv articles individually? If you end up needing the complete Crossref API catalog, then you'll want `crossref-works.json.xz`.

**Comment by boramalper** [comment]
I didn't know about these commands, many thanks!

In case anyone else (including you) stumbles upon the author disambiguation problem, here is an alternative solution I found:

[Semantic Scholar](https://semanticscholar.org/) provides openly accessible metadata about papers (even for those that don't have a DOI) such as AI extracted topics and also author information including a unique author ID (for [example](https://api.semanticscholar.org/v1/paper/arXiv:1904.06722)]. You can also download the data in bulk [here](https://api.semanticscholar.org/corpus/).

I don't know how exactly they do it, but they seem trustworthy enough and given the difficulty of the task as you have also mentioned, their solution seemed far better than whatever I could implement on my own.

Thanks once again! I am closing the issue. =)
