### ISSUE TITLE
What percent of scholarly publication DOIs are registered with Crossref?

### ISSUE THREAD

**Issue by dhimmel** [greenelab/crossref#3]
Let's use this issue to jot down notes related to what percent of scholarly publication DOIs are registered with Crossref.

As a refresher, there are [many](https://www.doi.org/RA_Coverage.html) DOI Registration Agencies (RA). For example, [EIDR](http://eidr.org/) is a DOI RA for entertainment, so you can actually [get DOI metadata](https://twitter.com/dhimmel/status/875375649334210560) for some porns! There is even discussion regarding DOIs for [construction products](https://www.bsigroup.com/en-GB/about-bsi/media-centre/press-releases/2015/october/-Major-research-project-launched-to-identify-the-next-step-in-digitising-the-construction-industry/?_ga=2.232463834.45554778.1497642879-798406953.1497642879). Shoutout to  @jenniferlin15 who helped me understand these intricacies of the DOI system.

For our analyses, we're most interested in DOIs for scholarly content. There are other RAs than Crossref that engage with scholarly content. Some examples are:

1. [mEDRA](https://www.medra.org/en/medra.htm) which "provides DOI registration services to publishers, academic institutions, research centres and intermediaries in Italy, in the EU market and internationally."
2. [DataCite](https://www.datacite.org/) which "provides persistent identifiers (DOIs) for research data."

We're mostly interested in cataloging all DOIs for scholarly publications in relation to our [Sci-Hub coverage project](https://github.com/greenelab/scihub).

**Comment by dhimmel** [comment]
# DOI Links on Wikipedia

The 2016 study, "[DOI Links on Wikipedia](https://doi.org/10.1007/978-3-319-49304-6_40)", provides the following discussion of the DOI RA breakdown:

> A prefix is assigned to a particular DOI registrant, such as publishing companies or academic societies. DOI registrants assign suffixes to their contents and register DOIs through DOI Registration Agencies (RAs). There are 10 RAs.

> Some RAs that handle scholarly resources (such as journal articles, books, and datasets) are CrossRef, JaLC, ISTIC, and DataCite. JaLC is the only RA in Japan, ISTIC is a Chinese RA, and DataCite is an RA for research data. As of April 2016, there are 76,944,396 DOIs registered by CrossRef (CrossRef DOIs); 23,422,068 DOIs by ISTIC (ISTIC DOIs); 6,614,478 DOIs by DataCite (DataCite DOIs); and 1,401,144 DOIs by JaLC (JaLC DOIs).

Table 2 of this study shows the breakdown of RAs for DOI links on Wikipedia as of March 2015. This Table is reproduced below:

| RA | enwiki | jawiki | zhwiki |
|----------|-----------|--------|--------|
| AIRITI | 2 | 0 | 0 |
| CrossRef | 1,463,052 | 27,900 | 36,202 |
| DataCite | 464 | 13 | 6 |
| ISTIC | 101 | 0 | 44 |
| JaLC | 9 | 549 | 0 |
| mEDRA | 647 | 5 | 9 |
| OPOCE | 176 | 2 | 3 |
| Public | 367 | 6 | 25 |
| Error | 9,412 | 324 | 380 |
| Total | 1,474,230 | 28,799 | 36,669 |

`enwiki` stands for the English Wikipedia; `jawiki` stands for the Japanese Wikipedia; `zhwiki` stands for the Chinese Wikipedia. The authors summarize:

> Table 2 shows the number of total DOI links for RAs. Most of DOI links in these Wikipedia are CrossRef DOIs. The second most-referenced DOI links in enwiki are mEDRA DOIs; those in jawiki are JaLC DOIs; those in zhwiki are ISTIC DOIs. Note that JaLC DOIs are not referenced in zhwiki, and ISTIC DOIs are not referenced in jawiki. In other words, the scholarly content in Japan tends to be referenced in jawiki, the content in China tends to be referenced in zhwiki.

From this table, we can compute the percent of all DOI links on wikipedia that are for Crossref registered DOIs:

+ English Wikipedia: 99.87944% = 1463052 / (1474230 - 9412)
+ Japanese Wikipedia: 97.98068% = 27900 / (28799 - 324)
+ Chinese Wikipedia: 99.76026% = 36202 / (36669 - 380)

Therefore, it's clear that for DOIs that are actually referenced, they overwhelming were registered with Crossref. There is a small language effect with links in the Japanese Wikipedia using other registrars than Crossref about 2% of the time.

**Comment by dhimmel** [comment]
From the 2014 article [CrossRef developments and initiatives](https://doi.org/10.6087/kcse.2014.1.13):

> Not all of these DOIs will have been issued through CrossRef and other agencies like DataCite, mEDRA, Movie Labs and CNKI can assign DOIs to content as well. Geoffrey Bilder’s recent blog-post ‘DOIs unambiguously and persistently identify published, trustworthy, citable online scholarly literature. Right?’ is an interesting expansion on this point and is useful to bear in mind that not all DOIs are CrossRef DOIs.

In @gbilder's [referenced blog post](https://www.crossref.org/blog/dois-unambiguously-and-persistently-identify-published-trustworthy-citable-online-scholarly-literature-right/), there's a nice visualization defining scope overlap between the RAs

![](https://www.crossref.org/wp/blog/uploads/2013/06/ra_overlap.png)

The RAs in the top right corner are the relevant ones for scholarly content.

**Comment by dhimmel** [comment]
From the [FAQ page](https://www.doi.org/faq.html) at doi.org on June 16, 2017:

> **4. How many DOI names are there, and who uses them?**
> Approximately 133 million DOIs have been assigned through a federation of Registration Agencies world-wide with an annual growth rate of 16%. See the factsheet DOI Key Facts and the DOI Handbook, 2 Numbering.

At this time, the Crossref API reports 89 million DOIs. Specifically https://api.crossref.org/works?rows=1 returns `"total-results":89216081`. Although these numbers are likely not from the exact same point in time, we can estimate that 66.9% = 89 / 133 of DOIs are registered by Crossref.

**Comment by dwhly** [comment]
I found the above statistic handy.  

I just polled the Crossref API again today, and got `"total-results":99085806`  DOIs.  Approximately 13 months have transpired since 89 million was returned, so we can surmise that Crossref is issuing 12/13 = x/9869725 or approx 9.1M DOIs per year (over the last year-- a number which might be increasing?).
